//! `bindgen`: regenerates `bela-sys/src/bindings.rs` from the vendored
//! Bela headers.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use bindgen::callbacks::ParseCallbacks;

const TARGET: &str = "aarch64-unknown-linux-gnu";

/// The package the generated file belongs to, and so the one whose
/// edition decides how it is formatted.
const PACKAGE: &str = "bela-sys";

// The defines the Bela build system compiles with on the Bela Gem
// (captured from a verbose on-board build; see docs/board-facts.md).
// They gate parts of the header surface, so bindgen must see them too.
const BELA_DEFINES: &[&str] = &[
    "-DBELA_USE_POLL",
    "-DENABLE_PRU_UIO=0",
    "-DENABLE_PRU_RPROC=1",
    "-DIS_AM62_PB2",
    "-DIS_AM62",
    "-DBELA_HAS_GPIO",
    "-DBELA_HAS_PRU_AND_MCASP",
    "-DBELA_RT_WRAP(call)=call",
    "-DBELA_EVL",
    "-DNDEBUG",
];

/// Drops one comment bindgen would otherwise attach to a function.
///
/// `GPIOcontrol.h` puts a banner over the block of `gpio_*`
/// declarations — a heading for the thirteen, not a description of the
/// first of them — and bindgen lifts it onto `gpio_setup`, which then
/// carries `gpio_functions` as its summary line on docs.rs while its
/// twelve neighbours carry nothing. Every other comment is passed
/// through untouched.
/// Records whether it matched, because a silent miss is the failure
/// worth catching: nothing about a banner that survives is an error.
#[derive(Debug)]
struct DropFamilyBanner(Arc<AtomicBool>);

impl ParseCallbacks for DropFamilyBanner {
    fn process_comment(&self, comment: &str) -> Option<String> {
        comment.trim().eq("gpio_functions").then(|| {
            self.0.store(true, Ordering::Relaxed);
            String::new()
        })
    }
}

pub(crate) fn generate(root: &Path, sysroot: Option<PathBuf>) {
    let vendor = root.join("bela-sys/vendor/bela");
    let source = fs::read_to_string(vendor.join("SOURCE")).expect("read vendor SOURCE file");
    let source = source.trim();
    let out = root.join("bela-sys/src/bindings.rs");

    // Set by `DropFamilyBanner` when it matches, and asserted below.
    // bindgen consults only the *last* registered `parse_callbacks`
    // for comments, so this one both loses to any registered after it
    // and suppresses `process_comment` on any registered before it.
    let banner_dropped = Arc::new(AtomicBool::new(false));

    let mut builder = bindgen::Builder::default()
        .header(root.join("bela-sys/wrapper.h").display().to_string())
        .clang_arg(format!("--target={TARGET}"))
        .clang_arg(format!("-I{}", vendor.join("include").display()))
        .clang_args(BELA_DEFINES)
        .use_core()
        .allowlist_type("Bela.*")
        .allowlist_type("AuxiliaryTask")
        .allowlist_function("Bela_.*")
        .allowlist_function("rt_.*")
        // The sysfs GPIO and LED family from `GPIOcontrol.h`, which
        // `Bela.h` includes and `libbela` exports. It is the only way
        // this crate offers to reach a pin that is not one of the
        // sixteen digital channels a `BelaContext` carries, or to
        // reach any pin at all outside a render callback; libbela's
        // own `Gpio` reaches one through the registers instead, which
        // is a different thing and not bound here. `PIN_DIRECTION`
        // and `PIN_VALUE` are the vocabulary its `out_flag` and
        // `value` arguments are written in, so they come with the
        // functions.
        .allowlist_function("gpio_.*")
        .allowlist_function("led_set_trigger")
        .allowlist_type("PIN_.*")
        .allowlist_var("BELA_.*")
        .allowlist_var("DEFAULT_.*")
        .prepend_enum_name(false)
        // The FILE* / va_list printf variants would drag glibc internals
        // into the bindings and are not usable from Rust anyway.
        .blocklist_function("(rt|Bela)_v?fprintf")
        .blocklist_function("(rt|Bela)_vprintf")
        .blocklist_type("^FILE$")
        .blocklist_type("^_IO_FILE$")
        .blocklist_type("^_IO_marker$")
        .blocklist_type("^_IO_codecvt$")
        .blocklist_type("^_IO_wide_data$")
        .blocklist_type("^_IO_lock_t$")
        .blocklist_type("^__off_t$")
        .blocklist_type("^__off64_t$")
        .blocklist_type("^va_list$")
        .blocklist_type("^__gnuc_va_list$")
        .blocklist_type("^__BindgenOpaqueArray$")
        .derive_default(true)
        .parse_callbacks(Box::new(DropFamilyBanner(Arc::clone(&banner_dropped))))
        // Formatting is left to `cargo fmt`; see `format`.
        .formatter(bindgen::Formatter::None)
        .raw_line(format!(
            "//! Bindings to the Bela core API, generated by `cargo xtask bindgen`\n\
             //! from Bela headers vendored from: {source}. Do not edit by hand."
        ));
    if let Some(sysroot) = sysroot {
        builder = builder.clang_arg(format!("--sysroot={}", sysroot.display()));
    }

    let bindings = builder.generate().expect("bindgen failed");
    // Assert the callback matched rather than that its text is gone.
    // The two ways it stops working are a later `parse_callbacks`
    // displacing it and the vendored banner being reworded, and only
    // the first leaves `gpio_functions` behind to search for: a
    // reworded banner would be attached to `gpio_setup` under its new
    // name, which is the outcome this guards against, while a search
    // for the old name passed. Neither is an error to bindgen, and no
    // CI job regenerates this file to notice.
    assert!(
        banner_dropped.load(Ordering::Relaxed),
        "DropFamilyBanner never matched: a later parse_callbacks has \
         displaced it, or GPIOcontrol.h's family banner was reworded, \
         or the gpio_* family is no longer being generated at all"
    );
    bindings.write_to_file(&out).expect("write bindings.rs");
    format(root);
    println!("wrote {}", out.display());
}

/// Formats the generated file the way the rest of the workspace is
/// formatted.
///
/// bindgen can run rustfmt itself, and used to. It picks the edition to
/// format for from its own idea of the current Rust release rather than
/// from this workspace, and that idea stops at the newest release the
/// bindgen release knows about — 1.82 here, whose latest edition is
/// 2021. The two editions disagree about where a wrapped return type
/// goes, so `cargo xtask bindgen` and `cargo fmt` each rewrote the
/// other's output, and a rerun of the task reported a diff that said
/// nothing about the headers it had read.
///
/// Deferring to `cargo fmt` leaves one authority on formatting, the one
/// CI already checks, and it reads the edition from `Cargo.toml`
/// instead of from a second copy kept here.
fn format(root: &Path) {
    // `CARGO` is set for anything cargo runs, which is how this task is
    // run; the fallback is for a directly invoked binary.
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let status = Command::new(cargo)
        .args(["fmt", "--package", PACKAGE, "--manifest-path"])
        .arg(root.join("Cargo.toml"))
        .status()
        .expect("run cargo fmt");
    assert!(status.success(), "cargo fmt failed: {status}");
}
