//! `bindgen`: regenerates `bela-sys/src/bindings.rs` from the vendored
//! Bela headers.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const TARGET: &str = "aarch64-unknown-linux-gnu";

/// The package the generated file belongs to, and so the one whose
/// edition decides how it is formatted.
const PACKAGE: &str = "bela-sys";

// The defines the Bela build system compiles with on the Bela Gem
// (captured from a verbose on-board build; see docs/board-facts.md).
// They gate parts of the header surface, so bindgen must see them too.
const BELA_DEFINES: &[&str] = &[
    "-DBELA_USE_POLL",
    "-DENABLE_PRU_UIO=0",
    "-DENABLE_PRU_RPROC=1",
    "-DIS_AM62_PB2",
    "-DIS_AM62",
    "-DBELA_HAS_GPIO",
    "-DBELA_HAS_PRU_AND_MCASP",
    "-DBELA_RT_WRAP(call)=call",
    "-DBELA_EVL",
    "-DNDEBUG",
];

pub(crate) fn generate(root: &Path, sysroot: Option<PathBuf>) {
    let vendor = root.join("bela-sys/vendor/bela");
    let source = fs::read_to_string(vendor.join("SOURCE")).expect("read vendor SOURCE file");
    let source = source.trim();
    let out = root.join("bela-sys/src/bindings.rs");

    let mut builder = bindgen::Builder::default()
        .header(root.join("bela-sys/wrapper.h").display().to_string())
        .clang_arg(format!("--target={TARGET}"))
        .clang_arg(format!("-I{}", vendor.join("include").display()))
        .clang_args(BELA_DEFINES)
        .use_core()
        .allowlist_type("Bela.*")
        .allowlist_type("AuxiliaryTask")
        .allowlist_function("Bela_.*")
        .allowlist_function("rt_.*")
        .allowlist_var("BELA_.*")
        .allowlist_var("DEFAULT_.*")
        // The FILE* / va_list printf variants would drag glibc internals
        // into the bindings and are not usable from Rust anyway.
        .blocklist_function("(rt|Bela)_v?fprintf")
        .blocklist_function("(rt|Bela)_vprintf")
        .derive_default(true)
        // Formatting is left to `cargo fmt`; see `format`.
        .formatter(bindgen::Formatter::None)
        .raw_line(format!(
            "//! Bindings to the Bela core API, generated by `cargo xtask bindgen`\n\
             //! from Bela headers vendored from: {source}. Do not edit by hand."
        ));
    if let Some(sysroot) = sysroot {
        builder = builder.clang_arg(format!("--sysroot={}", sysroot.display()));
    }

    let bindings = builder.generate().expect("bindgen failed");
    bindings.write_to_file(&out).expect("write bindings.rs");
    format(root);
    println!("wrote {}", out.display());
}

/// Formats the generated file the way the rest of the workspace is
/// formatted.
///
/// bindgen can run rustfmt itself, and used to. It picks the edition to
/// format for from its own idea of the current Rust release rather than
/// from this workspace, and that idea stops at the newest release the
/// bindgen release knows about — 1.82 here, whose latest edition is
/// 2021. The two editions disagree about where a wrapped return type
/// goes, so `cargo xtask bindgen` and `cargo fmt` each rewrote the
/// other's output, and a rerun of the task reported a diff that said
/// nothing about the headers it had read.
///
/// Deferring to `cargo fmt` leaves one authority on formatting, the one
/// CI already checks, and it reads the edition from `Cargo.toml`
/// instead of from a second copy kept here.
fn format(root: &Path) {
    // `CARGO` is set for anything cargo runs, which is how this task is
    // run; the fallback is for a directly invoked binary.
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let status = Command::new(cargo)
        .args(["fmt", "--package", PACKAGE, "--manifest-path"])
        .arg(root.join("Cargo.toml"))
        .status()
        .expect("run cargo fmt");
    assert!(status.success(), "cargo fmt failed: {status}");
}
