//! Repository tasks. Currently only `bindgen`: regenerates
//! `bela-sys/src/bindings.rs` from the vendored Bela headers.

use std::path::PathBuf;
use std::{env, fs, process};

const TARGET: &str = "aarch64-unknown-linux-gnu";

fn main() {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("bindgen") => {
            let mut sysroot = env::var_os("BELA_SYSROOT").map(PathBuf::from);
            while let Some(arg) = args.next() {
                match arg.as_str() {
                    "--sysroot" => {
                        let value = args.next().unwrap_or_else(|| usage());
                        sysroot = Some(PathBuf::from(value));
                    }
                    _ => usage(),
                }
            }
            generate(sysroot);
        }
        _ => usage(),
    }
}

fn usage() -> ! {
    eprintln!("usage: cargo xtask bindgen [--sysroot <dir>]");
    eprintln!();
    eprintln!("The sysroot must provide aarch64-linux libc headers (defaults to");
    eprintln!("the BELA_SYSROOT environment variable). See bela-sys/README.md.");
    process::exit(2);
}

fn generate(sysroot: Option<PathBuf>) {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives one level below the repository root")
        .to_path_buf();
    let vendor = root.join("bela-sys/vendor/bela");
    let commit = fs::read_to_string(vendor.join("COMMIT")).expect("read vendor COMMIT file");
    let commit = commit.trim();
    let out = root.join("bela-sys/src/bindings.rs");

    let mut builder = bindgen::Builder::default()
        .header(root.join("bela-sys/wrapper.h").display().to_string())
        .clang_arg(format!("--target={TARGET}"))
        .clang_arg(format!("-I{}", vendor.join("include").display()))
        .use_core()
        .allowlist_type("Bela.*")
        .allowlist_type("AuxiliaryTask")
        .allowlist_function("Bela_.*")
        .allowlist_function("rt_.*")
        .allowlist_var("BELA_.*")
        .allowlist_var("DEFAULT_.*")
        // The FILE* / va_list printf variants would drag glibc internals
        // into the bindings and are not usable from Rust anyway.
        .blocklist_function("(rt|Bela)_v?fprintf")
        .blocklist_function("(rt|Bela)_vprintf")
        .derive_default(true)
        .formatter(bindgen::Formatter::Rustfmt)
        .raw_line(format!(
            "//! Bindings to the Bela core API, generated by `cargo xtask bindgen`\n\
             //! from BelaPlatform/Bela commit `{commit}`. Do not edit by hand."
        ));
    if let Some(sysroot) = sysroot {
        builder = builder.clang_arg(format!("--sysroot={}", sysroot.display()));
    }

    let bindings = builder.generate().expect("bindgen failed");
    bindings.write_to_file(&out).expect("write bindings.rs");
    println!("wrote {}", out.display());
}
